### ISSUE TITLE
Can't call setState on an unmounted component.

### ISSUE THREAD

**Issue by samuelhauser** [taming-the-state-in-react/gatsby-firebase-authentication#12]
First of all I would like to thank you for the great work.

In dev mode i have the following error in the console:

![error](https://user-images.githubusercontent.com/1894064/46520286-b3549e80-c87b-11e8-8ede-6e540b6730be.jpg)

Does anyone have a solution to this problem?

**Comment by rwieruch** [comment]
Check [this chapter](https://github.com/the-road-to-learn-react/the-road-to-learn-react/blob/master/manuscript/chapter3.md#axios-instead-of-fetch) from my book. There you will find a way on how to avoid the warning. After all, it is only a warning and you don't need to worry about it too much.

**Comment by samuelhauser** [comment]
Thank you for your quick answer. I will definitely have a look at it. If I have any more questions, I'll get back to you.
