### ISSUE TITLE
Error: A continue URL must be provided in the request.

### ISSUE THREAD

**Issue by ChaseWoodhams** [taming-the-state-in-react/gatsby-firebase-authentication#43]
I am a new developer so this could be something simple but I am not able to send a validation email after successfully signing up a user. I have searched through the code as much as possible but I don't where or how I can declare a Continue URL

**Comment by joyOf** [comment]
+1

**Comment by rwieruch** [comment]
Did you provide your `REACT_APP_CONFIRMATION_EMAIL_REDIRECT` in your .env file? You can read more about it over here https://www.robinwieruch.de/react-firebase-email-verification/

**Comment by leoktsbnsk** [comment]
Thank you very much for your reply! I have added indeed added a variable atm of writing this but it didn't help. So I decided to start over and now have a different problem, that is repeating over and over again. 

This is my .env file (this is the same as my domain, you can check)
`
REACT_APP_CONFIRMATION_EMAIL_REDIRECT=joy-story-today.firebaseapp.com
`
but
![image](https://user-images.githubusercontent.com/30351651/57198848-17595580-6f78-11e9-89c6-027766cbc678.png)
This is from a website on firebase

![image](https://user-images.githubusercontent.com/30351651/57198858-30fa9d00-6f78-11e9-9ddb-853508bd1dbd.png)
And this one is from a local project

**Comment by joyOf** [comment]
> Did you provide your `REACT_APP_CONFIRMATION_EMAIL_REDIRECT` in your .env file? You can read more about it over here https://www.robinwieruch.de/react-firebase-email-verification/

Thank you very much for your response. I have provided the redirect link in the .env file as required. However, I ran into different problems along the way, errors in the console like:
1. The API key is not valid (but I double checked and it was valid) 
2. The firebase duplication error
3. Promise error in the console in the browser
4. The email doesn't send out
...

So I was starting over and over again from cloning the repo till the firebase deploy and was anyways running in the same issues.

My steps were the following:
1. Clone the repo (+ `npm install` + `npm run`)
2. Create Firebase project in the console and get the config data
3. Add the Firebase config to `.env`  (I suppose if I don't have two configurations I just need to use .env without the `REACT_APP_CONFIRMATION_EMAIL_REDIRECT`) + add storage rules in the file of the project (and to the console). I tried to add both production and development redirect and it didn't seem to do the job for me
4. `firebase init` where I choose hosting, database and storage (I need it later for my app)
5. `gatsby build` + `firebase deploy`

I have started many times already and can't seem to understand how to replicate the errors or what's causing them. 

I would heartily appreciate any help! Thanks in advance!

**Comment by ChaseWoodhams** [comment]
I was able to solve this issue myself by pulling down a fresh repo and then updating my .env to the .env.development specified in the Readme. I used a console log to determine that the credentials werent being passed properly with just the .env specified. Also make sure your .env.development is in the root directory.

**Comment by rwieruch** [comment]
Perfect @ChaseWoodhams Thanks for letting us know that it worked and how to debug the problem. I think this will help other people as well 🚀
