### ISSUE TITLE
Error occurred while trying to proxy to: localhost:8000/ => (after updating packages )

### ISSUE THREAD

**Issue by thelovesmith** [taming-the-state-in-react/gatsby-firebase-authentication#51]
I keep getting this HPM Error when i try to visit my page after running Gatsby Develop. The project compiles Successfully but then I get this error in the browser 

>  error occurred while trying to proxy to: localhost:8000/ 

and this in the terminal 

> error [HPM] Error occurred while trying to proxy request / from localhost:8000 to http://localhost:4000 (ECONNREFUSED)

once I remove this from the 
-config.js file it works and the pages generated in the browser:

```
module.exports = {
    developMiddleware: app => {
        app.use(
            proxy({
                target: "http://localhost:4000",
            })
        )
    },
}
```

However, I then get this error in the terminal :

> Error loading a result for the page query in "/404.html". Query was not run and no cached result was found.
> Page not found /404.html
 
Even though I get this error the pages work and the project Compiles successfully. 

I Really want to know how to fix the first error without getting rid of the proxy in the config file. 

Here is my repo:
https://github.com/thelovesmith/Island-Stream-Web-MVP

**Comment by hindsricardo** [comment]
@thelovesmith did you resolve this issue? I am having the same problem
