### ISSUE TITLE
Signin Shows blank

### ISSUE THREAD

**Issue by Douglashdaniel** [taming-the-state-in-react/gatsby-firebase-authentication#6]
I followed the instructions, when running gatsby develop, the build failed and i needed to run npm install --save react-router-dom
After that it would successfully compile.
after loading local host in my browser, when i click Sign In it loads a blank page. 
How do i resolve this issue?

**Comment by rwieruch** [comment]
Thanks for reaching out! Would you be able to open up a PR where react-router-dom is added to the package.json?

Otherwise we recently upgraded to Gatsby 2.0 and I didn't check the application since then https://github.com/taming-the-state-in-react/gatsby-firebase-authentication/pull/5 Maybe something has changed regarding this. (CC @ckj )

**Comment by dajocarter** [comment]
I added react-router-dom to the package.json here #7 

Only the landing page "/" and the passwordForget page "/pw-forget" are able to load. Every other page fails to load for the same reason.

```
Uncaught Error: You should not use <Route> or withRouter() outside a <Router>
```

For instance, on the sign in page you get

```
The above error occurred in the <Route> component:
in Route (created by withRouter(SignInForm))
    in withRouter(SignInForm) (at signin.js:11)
    in div (at layout.js:25)
    in div (at layout.js:20)
    in StaticQuery (at layout.js:9)
    in Layout (at withAuthentication.js:31)
    in WithAuthentication (at signin.js:9)
    in SignInPage (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (created by RouteHandler)
    in ScrollContext (at root.js:82)
    in RouteHandler (created by Root)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by LocationProvider)
    in LocationProvider
    in Location
    in Router (created by Root)
    in Root (at root.js:111)
    in _default (created by HotExported_default)
    in AppContainer (created by HotExported_default)
    in HotExported_default (at app.js:55)

React will try to recreate this component tree from scratch using the error boundary you provided, LocationProvider.
```

**Comment by joshbuchea** [comment]
+1 running into the same issue as @Douglashdaniel

**Comment by joshbuchea** [comment]
Perhaps something do with Gatsby v2 swapping out React Router for Reach Router?

**Comment by ckj** [comment]
@joshbuchea I think this is probably the case. 

@rwieruch it seems a lot has changed since I submitted the PR... perhaps it's best to revert the v2 change until things settle a bit more on Gatsby's end?

**Comment by oshentonaf** [comment]
I am getting the same problem of a routing issue in every page apart from the home, with Gatsby 2. Is this because of the change mentioned above?

**Comment by rwieruch** [comment]
@dajocarter I have merged your PR. Thanks for your help here!

Unfortunately I don't have any time to dive into this issue. Any chance to fix it without reverting Gatsby to an old version? it would be sad to remove all the efforts to upgrade it in the first place :)
